name: CI/CD Pipeline - Practica DevOps

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Copiar el repositorio al runner
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configurar emulación (requerido para builds limpios)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
# Paso temporal de depuración para verificar variables
      - name: Verificar secreto cargado
        run: |
          echo "Longitud de Username: ${#D_USER}"
          echo "Longitud de Token: ${#D_TOKEN}"
        env:
          D_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          D_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}           
        

      # 4. Autenticarse en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          
       

      # 5. Construir y publicar la imagen de Laravel
      - name: Build and push Laravel Image
        uses: docker/build-push-action@v6
        with:
          context: ./laravel-api
          file: ./laravel-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/agasaja-laravel:latest

      # 6. Construir y publicar la imagen de React
      - name: Build and push React Image
        uses: docker/build-push-action@v6
        with:
          context: ./reactfront
          file: ./reactfront/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/agasaja-react:latest
          build-args: |
            HTTP_PROXY=${{ secrets.HTTP_PROXY }}
            HTTPS_PROXY=${{ secrets.HTTPS_PROXY }}
